"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

added_num = 0
even_added = 0
i = 0
fib_lst = [0, 1]
even_fib = []

end_num = int(input("What is the end number? "))

while added_num < end_num:
    added_num = fib_lst[i] + fib_lst[i+1]
    fib_lst.append(added_num)
    i += 1
    if added_num % 2 == 0:
        even_fib.append(added_num)
fib_lst.pop()
print(fib_lst)

for i in range(len(even_fib)):
    even_added += even_fib[i]
print(even_fib)
print(even_added)
